version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=lendingplatform
    restart: unless-stopped

  app:
    build: .
    container_name: solid_lending_platform
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
      - "SPRING_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/lendingplatform"
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: